default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: angelo_souza
  password: 1234

development:
  <<: *default
  database: cateqapp_development

test:
  <<: *default
  database: cateqapp_test

production:
  <<: *default
  database: cateqapp_production
  username: cateqapp
  password: <%= ENV['CATEQAPP_DATABASE_PASSWORD'] %>
